#pragma once
#include "Common.h"

enum ReplicaComponentID
{
	REPLICA_COMPONENT_ID_108 = 108,
	REPLICA_COMPONENT_ID_MODULE_ASSEMBLY = 61,
	REPLICA_COMPONENT_ID_CONTROLLABLE_PHYSICS = 1,
	REPLICA_COMPONENT_ID_SIMPLE_PHYSICS = 3,
	REPLICA_COMPONENT_ID_RIGID_BODY_PHANTOM_PHYSICS = 20,
	REPLICA_COMPONENT_ID_VEHICLE_PHYSICS = 30,
	REPLICA_COMPONENT_ID_PHANTOM_PHYSICS = 40,
	REPLICA_COMPONENT_ID_DESTRUCTIBLE = 7,
	REPLICA_COMPONENT_ID_COLLECTIBLE = 23,
	REPLICA_COMPONENT_ID_PET = 26,
	REPLICA_COMPONENT_ID_CHARACTER = 4,
	REPLICA_COMPONENT_ID_INVENTORY = 17,
	REPLICA_COMPONENT_ID_SCRIPT = 5,
	REPLICA_COMPONENT_ID_SKILL = 9,
	REPLICA_COMPONENT_ID_BASE_COMBAT_AI = 60,
	REPLICA_COMPONENT_ID_REBUILD = 48,
	REPLICA_COMPONENT_ID_MOVING_PLATFORM = 25,
	REPLICA_COMPONENT_ID_SWITCH = 49,
	REPLICA_COMPONENT_ID_VENDOR = 16,
	REPLICA_COMPONENT_ID_BOUNCER = 6,
	REPLICA_COMPONENT_ID_SCRIPTED_ACTIVITY = 39,
	REPLICA_COMPONENT_ID_RACING_CONTROL = 71,
	REPLICA_COMPONENT_ID_RENDER = 2,
	REPLICA_COMPONENT_ID_107 = 107
};

enum ReplicaSerializationID
{
	REPLICA_SERIALIZATION_ID_108 = 0,
	REPLICA_SERIALIZATION_ID_MODULE_ASSEMBLY,
	REPLICA_SERIALIZATION_ID_CONTROLLABLE_PHYSICS,
	REPLICA_SERIALIZATION_ID_SIMPLE_PHYSICS,
	REPLICA_SERIALIZATION_ID_RIGID_BODY_PHANTOM_PHYSICS,
	REPLICA_SERIALIZATION_ID_VEHICLE_PHYSICS,
	REPLICA_SERIALIZATION_ID_PHANTOM_PHYSICS,
	REPLICA_SERIALIZATION_ID_DESTRUCTIBLE,
	REPLICA_SERIALIZATION_ID_COLLECTIBLE,
	REPLICA_SERIALIZATION_ID_PET,
	REPLICA_SERIALIZATION_ID_CHARACTER,
	REPLICA_SERIALIZATION_ID_INVENTORY,
	REPLICA_SERIALIZATION_ID_SCRIPT,
	REPLICA_SERIALIZATION_ID_SKILL,
	REPLICA_SERIALIZATION_ID_BASE_COMBAT_AI,
	REPLICA_SERIALIZATION_ID_REBUILD,
	REPLICA_SERIALIZATION_ID_MOVING_PLATFORM,
	REPLICA_SERIALIZATION_ID_SWITCH,
	REPLICA_SERIALIZATION_ID_VENDOR,
	REPLICA_SERIALIZATION_ID_BOUNCER,
	REPLICA_SERIALIZATION_ID_SCRIPTED_ACTIVITY,
	REPLICA_SERIALIZATION_ID_RACING_CONTROL,
	REPLICA_SERIALIZATION_ID_RENDER,
	REPLICA_SERIALIZATION_ID_107,

	REPLICA_SERIALIZATION_ID_COUNT
};

class ReplicaComponent
{
public:
	ReplicaComponentID componentID;
	ReplicaSerializationID serializationID;

	virtual void writeToBitStream(BitStream* bitStream, bool isConstruction) {};
};