#include "ServerRoles.h"

ServerRole ServerRoles::fromZoneID(ZoneID zoneID)
{
	switch (zoneID)
	{

	case ZONE_ID_VENTURE_EXPLORER:
		return ServerRole::SERVER_ROLE_VENTURE_EXPLORER;

	case ZONE_ID_RETURN_TO_VENTURE_EXPLORER:
		return ServerRole::SERVER_ROLE_RETURN_TO_VENTURE_EXPLORER;

	case ZONE_ID_AVANT_GARDENS:
		return ServerRole::SERVER_ROLE_AVANT_GARDENS;

	case ZONE_ID_AVANT_GARDENS_SURVIVAL:
		return ServerRole::SERVER_ROLE_AVANT_GARDENS_SURVIVAL;

	case ZONE_ID_SPIDER_QUEEN_BATTLE:
		return ServerRole::SERVER_ROLE_SPIDER_QUEEN_BATTLE;

	case ZONE_ID_BLOCK_YARD:
		return ServerRole::SERVER_ROLE_BLOCK_YARD;

	case ZONE_ID_AVANT_GROVE:
		return ServerRole::SERVER_ROLE_AVANT_GROVE;

	case ZONE_ID_NIMBUS_STATION:
		return ServerRole::SERVER_ROLE_NIMBUS_STATION;

	case ZONE_ID_PET_COVE:
		return ServerRole::SERVER_ROLE_PET_COVE;

	case ZONE_ID_VERTIGO_LOOP_RACETRACK:
		return ServerRole::SERVER_ROLE_VERTIGO_LOOP_RACETRACK;

	case ZONE_ID_BATTLE_OF_NIMBUS_STATION:
		return ServerRole::SERVER_ROLE_BATTLE_OF_NIMBUS_STATION;

	case ZONE_ID_NIMBUS_ROCK:
		return ServerRole::SERVER_ROLE_NIMBUS_ROCK;

	case ZONE_ID_NIMBUS_ISLE:
		return ServerRole::SERVER_ROLE_NIMBUS_ISLE;

	case ZONE_ID_GNARLED_FOREST:
		return ServerRole::SERVER_ROLE_GNARLED_FOREST;

	case ZONE_ID_CANYON_COVE:
		return ServerRole::SERVER_ROLE_CANYON_COVE;

	case ZONE_ID_CHANTEY_SHANTEY:
		return ServerRole::SERVER_ROLE_CHANTEY_SHANTEY;

	case ZONE_ID_FORBIDDEN_VALLEY:
		return ServerRole::SERVER_ROLE_FORBIDDEN_VALLEY;

	case ZONE_ID_FORBIDDEN_VALLEY_DRAGON:
		return ServerRole::SERVER_ROLE_FORBIDDEN_VALLEY_DRAGON;

	case ZONE_ID_DRAGONMAW_CHASM:
		return ServerRole::SERVER_ROLE_DRAGONMAW_CHASM;

	case ZONE_ID_RAVEN_BLUFF:
		return ServerRole::SERVER_ROLE_RAVEN_BLUFF;

	case ZONE_ID_STARBASE_3001:
		return ServerRole::SERVER_ROLE_STARBASE_3001;

	case ZONE_ID_DEEP_FREEZE:
		return ServerRole::SERVER_ROLE_DEEP_FREEZE;

	case ZONE_ID_ROBOT_CITY:
		return ServerRole::SERVER_ROLE_ROBOT_CITY;

	case ZONE_ID_MOON_BASE:
		return ServerRole::SERVER_ROLE_MOON_BASE;

	case ZONE_ID_PORTABELLO:
		return ServerRole::SERVER_ROLE_PORTABELLO;

	case ZONE_ID_LEGO_CLUB:
		return ServerRole::SERVER_ROLE_LEGO_CLUB;

	case ZONE_ID_CRUX_PRIME:
		return ServerRole::SERVER_ROLE_CRUX_PRIME;

	case ZONE_ID_NEXUS_TOWER:
		return ServerRole::SERVER_ROLE_NEXUS_TOWER;

	case ZONE_ID_NINJAGO_MONASTERY:
		return ServerRole::SERVER_ROLE_NINJAGO_MONASTERY;

	case ZONE_ID_FRAKJAW_BATTLE:
		return ServerRole::SERVER_ROLE_FRAKJAW_BATTLE;

	default:
		return ServerRole::INVALID_SERVER_ROLE;

	}
}

string ServerRoles::toString(ServerRole serverRole)
{
	switch (serverRole)
	{

	case SERVER_ROLE_AUTHENTICATION:
		return "AuthenticationInstance";

	case SERVER_ROLE_CHARACTERS:
		return "CharactersInstance";

	case INVALID_SERVER_ROLE:
		return "INVALID_SERVER_ROLE";

	default:
		return "WorldInstance" + to_string(ServerRoles::toZoneID(serverRole));
		//return "WorldInstance" + to_string(ServerRoles::toZoneID(SERVER_ROLE_AVANT_GARDENS));

	}
}

ZoneID ServerRoles::toZoneID(ServerRole serverRole)
{
	switch (serverRole)
	{

	case SERVER_ROLE_VENTURE_EXPLORER:
		return ZoneID::ZONE_ID_VENTURE_EXPLORER;

	case SERVER_ROLE_RETURN_TO_VENTURE_EXPLORER:
		return ZoneID::ZONE_ID_RETURN_TO_VENTURE_EXPLORER;

	case SERVER_ROLE_AVANT_GARDENS:
		return ZoneID::ZONE_ID_AVANT_GARDENS;

	case SERVER_ROLE_AVANT_GARDENS_SURVIVAL:
		return ZoneID::ZONE_ID_AVANT_GARDENS_SURVIVAL;

	case SERVER_ROLE_SPIDER_QUEEN_BATTLE:
		return ZoneID::ZONE_ID_SPIDER_QUEEN_BATTLE;

	case SERVER_ROLE_BLOCK_YARD:
		return ZoneID::ZONE_ID_BLOCK_YARD;

	case SERVER_ROLE_AVANT_GROVE:
		return ZoneID::ZONE_ID_AVANT_GROVE;

	case SERVER_ROLE_NIMBUS_STATION:
		return ZoneID::ZONE_ID_NIMBUS_STATION;

	case SERVER_ROLE_PET_COVE:
		return ZoneID::ZONE_ID_PET_COVE;

	case SERVER_ROLE_VERTIGO_LOOP_RACETRACK:
		return ZoneID::ZONE_ID_VERTIGO_LOOP_RACETRACK;

	case SERVER_ROLE_BATTLE_OF_NIMBUS_STATION:
		return ZoneID::ZONE_ID_BATTLE_OF_NIMBUS_STATION;

	case SERVER_ROLE_NIMBUS_ROCK:
		return ZoneID::ZONE_ID_NIMBUS_ROCK;

	case SERVER_ROLE_NIMBUS_ISLE:
		return ZoneID::ZONE_ID_NIMBUS_ISLE;

	case SERVER_ROLE_GNARLED_FOREST:
		return ZoneID::ZONE_ID_GNARLED_FOREST;

	case SERVER_ROLE_CANYON_COVE:
		return ZoneID::ZONE_ID_CANYON_COVE;

	case SERVER_ROLE_CHANTEY_SHANTEY:
		return ZoneID::ZONE_ID_CHANTEY_SHANTEY;

	case SERVER_ROLE_FORBIDDEN_VALLEY:
		return ZoneID::ZONE_ID_FORBIDDEN_VALLEY;

	case SERVER_ROLE_FORBIDDEN_VALLEY_DRAGON:
		return ZoneID::ZONE_ID_FORBIDDEN_VALLEY_DRAGON;

	case SERVER_ROLE_DRAGONMAW_CHASM:
		return ZoneID::ZONE_ID_DRAGONMAW_CHASM;

	case SERVER_ROLE_RAVEN_BLUFF:
		return ZoneID::ZONE_ID_RAVEN_BLUFF;

	case SERVER_ROLE_STARBASE_3001:
		return ZoneID::ZONE_ID_STARBASE_3001;

	case SERVER_ROLE_DEEP_FREEZE:
		return ZoneID::ZONE_ID_DEEP_FREEZE;

	case SERVER_ROLE_ROBOT_CITY:
		return ZoneID::ZONE_ID_ROBOT_CITY;

	case SERVER_ROLE_MOON_BASE:
		return ZoneID::ZONE_ID_MOON_BASE;

	case SERVER_ROLE_PORTABELLO:
		return ZoneID::ZONE_ID_PORTABELLO;

	case SERVER_ROLE_LEGO_CLUB:
		return ZoneID::ZONE_ID_LEGO_CLUB;

	case SERVER_ROLE_CRUX_PRIME:
		return ZoneID::ZONE_ID_CRUX_PRIME;

	case SERVER_ROLE_NEXUS_TOWER:
		return ZoneID::ZONE_ID_NEXUS_TOWER;

	case SERVER_ROLE_NINJAGO_MONASTERY:
		return ZoneID::ZONE_ID_NINJAGO_MONASTERY;

	case SERVER_ROLE_FRAKJAW_BATTLE:
		return ZoneID::ZONE_ID_FRAKJAW_BATTLE;

	default:
		return ZoneID::INVALID_ZONE_ID;

	}
}
