#pragma once
#include "Common.h"
#include "ZoneIDs.h"

enum ServerRole
{
	SERVER_ROLE_AUTHENTICATION,
	SERVER_ROLE_CHARACTERS,
	SERVER_ROLE_VENTURE_EXPLORER,
	SERVER_ROLE_RETURN_TO_VENTURE_EXPLORER,
	SERVER_ROLE_AVANT_GARDENS,
	SERVER_ROLE_AVANT_GARDENS_SURVIVAL,
	SERVER_ROLE_SPIDER_QUEEN_BATTLE,
	SERVER_ROLE_BLOCK_YARD,
	SERVER_ROLE_AVANT_GROVE,
	SERVER_ROLE_NIMBUS_STATION,
	SERVER_ROLE_PET_COVE,
	SERVER_ROLE_VERTIGO_LOOP_RACETRACK,
	SERVER_ROLE_BATTLE_OF_NIMBUS_STATION,
	SERVER_ROLE_NIMBUS_ROCK,
	SERVER_ROLE_NIMBUS_ISLE,
	SERVER_ROLE_GNARLED_FOREST,
	SERVER_ROLE_CANYON_COVE,
	SERVER_ROLE_CHANTEY_SHANTEY,
	SERVER_ROLE_FORBIDDEN_VALLEY,
	SERVER_ROLE_FORBIDDEN_VALLEY_DRAGON,
	SERVER_ROLE_DRAGONMAW_CHASM,
	SERVER_ROLE_RAVEN_BLUFF,
	SERVER_ROLE_STARBASE_3001,
	SERVER_ROLE_DEEP_FREEZE,
	SERVER_ROLE_ROBOT_CITY,
	SERVER_ROLE_MOON_BASE,
	SERVER_ROLE_PORTABELLO,
	SERVER_ROLE_LEGO_CLUB,
	SERVER_ROLE_CRUX_PRIME,
	SERVER_ROLE_NEXUS_TOWER,
	SERVER_ROLE_NINJAGO_MONASTERY,
	SERVER_ROLE_FRAKJAW_BATTLE,

	SERVER_ROLE_COUNT,
	INVALID_SERVER_ROLE
};

class ServerRoles
{
public:
	static ServerRole fromZoneID(ZoneID zoneID);
	static string toString(ServerRole serverRole);
	static ZoneID toZoneID(ServerRole serverRole);
};