#pragma once
#include "Common.h"
#include "ServerRoles.h"

enum RemoteConnectionType : unsigned short
{
	RCT_GENERAL = 0,
	RCT_CLIENT_TO_AUTH = 1,
	RCT_CHAT = 2,
	RCT_CLIENT_TO_WORLD = 4,
	RCT_WORLD_TO_CLIENT = 5
};

enum GeneralPacketID : unsigned long
{
	GENERAL_PACKET_VERSION_CONFIRM,
	GENERAL_PACKET_DISCONNECT_NOTIFY,
	GENERAL_PACKET_GENERAL_NOTIFY
};

enum ChatPacketID : unsigned long
{
	CHAT_PACKET_LOGIN_SESSION_NOTIFY,
	CHAT_PACKET_GENERAL_CHAT_MESSAGE,
	CHAT_PACKET_PRIVATE_CHAT_MESSAGE,
	CHAT_PACKET_USER_CHANNEL_CHAT_MESSAGE,
	CHAT_PACKET_WORLD_DISCONNECT_REQUEST,
	CHAT_PACKET_WORLD_PROXIMITY_RESPONSE,
	CHAT_PACKET_WORLD_PARCEL_RESPONSE,
	CHAT_PACKET_ADD_FRIEND_REQUEST,
	CHAT_PACKET_ADD_FRIEND_RESPONSE,
	CHAT_PACKET_REMOVE_FRIEND,
	CHAT_PACKET_GET_FRIENDS_LIST,
	CHAT_PACKET_ADD_IGNORE,
	CHAT_PACKET_REMOVE_IGNORE,
	CHAT_PACKET_GET_IGNORE_LIST,
	CHAT_PACKET_TEAM_MISSED_INVITE_CHECK,
	CHAT_PACKET_TEAM_INVITE,
	CHAT_PACKET_TEAM_INVITE_RESPONSE,
	CHAT_PACKET_TEAM_KICK,
	CHAT_PACKET_TEAM_LEAVE,
	CHAT_PACKET_TEAM_SET_LOOT,
	CHAT_PACKET_TEAM_SET_LEADER,
	CHAT_PACKET_TEAM_GET_STATUS,
	CHAT_PACKET_GUILD_CREATE,
	CHAT_PACKET_GUILD_INVITE,
	CHAT_PACKET_GUILD_INVITE_RESPONSE,
	CHAT_PACKET_GUILD_LEAVE,
	CHAT_PACKET_GUILD_KICK,
	CHAT_PACKET_GUILD_GET_STATUS,
	CHAT_PACKET_GUILD_GET_ALL,
	CHAT_PACKET_SHOW_ALL,
	CHAT_PACKET_BLUEPRINT_MODERATED,
	CHAT_PACKET_BLUEPRINT_MODEL_READY,
	CHAT_PACKET_PROPERTY_READY_FOR_APPROVAL,
	CHAT_PACKET_PROPERTY_MODERATION_CHANGED,
	CHAT_PACKET_PROPERTY_BUILDMODE_CHANGED,
	CHAT_PACKET_PROPERTY_BUILDMODE_CHANGED_REPORT,
	CHAT_PACKET_MAIL,
	CHAT_PACKET_WORLD_INSTANCE_LOCATION_REQUEST,
	CHAT_PACKET_REPUTATION_UPDATE,
	CHAT_PACKET_SEND_CANNED_TEXT,
	CHAT_PACKET_GMLEVEL_UPDATE,
	CHAT_PACKET_CHARACTER_NAME_CHANGE_REQUEST,
	CHAT_PACKET_CSR_REQUEST,
	CHAT_PACKET_CSR_REPLY,
	CHAT_PACKET_GM_KICK,
	CHAT_PACKET_GM_ANNOUNCE,
	CHAT_PACKET_GM_MUTE,
	CHAT_PACKET_ACTIVITY_UPDATE,
	CHAT_PACKET_WORLD_ROUTE_PACKET,
	CHAT_PACKET_GET_ZONE_POPULATIONS,
	CHAT_PACKET_REQUEST_MINIMUM_CHAT_MODE,
	CHAT_PACKET_REQUEST_MINIMUM_CHAT_MODE_PRIVATE,
	CHAT_PACKET_MATCH_REQUEST,
	CHAT_PACKET_UGCMANIFEST_REPORT_MISSING_FILE,
	CHAT_PACKET_UGCMANIFEST_REPORT_DONE_FILE,
	CHAT_PACKET_UGCMANIFEST_REPORT_DONE_BLUEPRINT,
	CHAT_PACKET_UGCC_REQUEST,
	CHAT_PACKET_WHO,
	CHAT_PACKET_WORLD_PLAYERS_PET_MODERATED_ACKNOWLEDGE,
	CHAT_PACKET_ACHIEVEMENT_NOTIFY,
	CHAT_PACKET_GM_CLOSE_PRIVATE_CHAT_WINDOW,
	CHAT_PACKET_UNEXPECTED_DISCONNECT,
	CHAT_PACKET_PLAYER_READY,
	CHAT_PACKET_GET_DONATION_TOTAL,
	CHAT_PACKET_UPDATE_DONATION,
	CHAT_PACKET_PRG_CSR_COMMAND,
	CHAT_PACKET_HEARTBEAT_REQUEST_FROM_WORLD,
	CHAT_PACKET_UPDATE_FREE_TRIAL_STATUS
};

enum ClientToAuthPacketID : unsigned long
{
	CLIENT_AUTH_PACKET_LOGIN_REQUEST,
	CLIENT_AUTH_PACKET_LOGOUT_REQUEST,
	CLIENT_AUTH_PACKET_CREATE_NEW_ACCOUNT_REQUEST,
	CLIENT_AUTH_PACKET_LEGOINTERFACE_AUTH_RESPONSE,
	CLIENT_AUTH_PACKET_SESSIONKEY_RECEIVED_CONFIRM,
	CLIENT_AUTH_PACKET_RUNTIME_CONFIG
};

enum ClientToWorldPacketID : unsigned long
{
	CLIENT_WORLD_UNKNOWN,
	CLIENT_WORLD_VALIDATION,
	CLIENT_WORLD_CHARACTER_LIST_REQUEST,
	CLIENT_WORLD_CHARACTER_CREATE_REQUEST,
	CLIENT_WORLD_LOGIN_REQUEST,
	CLIENT_WORLD_GAME_MSG,
	CLIENT_WORLD_CHARACTER_DELETE_REQUEST,
	CLIENT_WORLD_CHARACTER_RENAME_REQUEST,
	CLIENT_WORLD_HAPPY_FLOWER_MODE_NOTIFY,
	CLIENT_WORLD_SLASH_RELOAD_MAP,
	CLIENT_WORLD_SLASH_PUSH_MAP_REQUEST,
	CLIENT_WORLD_SLASH_PUSH_MAP,
	CLIENT_WORLD_SLASH_PULL_MAP,
	CLIENT_WORLD_LOCK_MAP_REQUEST,
	CLIENT_WORLD_GENERAL_CHAT_MESSAGE,
	CLIENT_WORLD_HTTP_MONITOR_INFO_REQUEST,
	CLIENT_WORLD_SLASH_DEBUG_SCRIPTS,
	CLIENT_WORLD_MODELS_CLEAR,
	CLIENT_WORLD_EXHIBIT_INSERT_MODEL,
	CLIENT_WORLD_LEVEL_LOAD_COMPLETE,
	CLIENT_WORLD_TMP_GUILD_CREATE,
	CLIENT_WORLD_ROUTE_PACKET,
	CLIENT_WORLD_POSITION_UPDATE,
	CLIENT_WORLD_MAIL,
	CLIENT_WORLD_WORD_CHECK,
	CLIENT_WORLD_STRING_CHECK,
	CLIENT_WORLD_GET_PLAYERS_IN_ZONE,
	CLIENT_WORLD_REQUEST_UGC_MANIFEST_INFO,
	CLIENT_WORLD_BLUEPRINT_GET_ALL_DATA_REQUEST,
	CLIENT_WORLD_CANCEL_MAP_QUEUE,
	CLIENT_WORLD_HANDLE_FUNNESS,
	CLIENT_WORLD_FAKE_PRG_CSR_MESSAGE,
	CLIENT_WORLD_REQUEST_FREE_TRIAL_REFRESH,
	CLIENT_WORLD_GM_SET_FREE_TRIAL_STATUS,
	CLIENT_WORLD_TOP_FIVE_ISSUES_REQUEST,
	CLIENT_WORLD_UGC_DOWNLOAD_FAILED_1,
	CLIENT_WORLD_UGC_DOWNLOAD_FAILED_2 = 120
};

enum WorldToClientPacketID
{
	WORLD_CLIENT_LOGIN_RESPONSE,
	WORLD_CLIENT_LOGOUT_RESPONSE,
	WORLD_CLIENT_LOAD_STATIC_ZONE,
	WORLD_CLIENT_CREATE_OBJECT,
	WORLD_CLIENT_CREATE_CHARACTER,
	WORLD_CLIENT_CREATE_CHARACTER_EXTENDED,
	WORLD_CLIENT_CHARACTER_LIST_RESPONSE,
	WORLD_CLIENT_CHARACTER_CREATE_RESPONSE,
	WORLD_CLIENT_CHARACTER_RENAME_RESPONSE,
	WORLD_CLIENT_CHAT_CONNECT_RESPONSE,
	WORLD_CLIENT_AUTH_ACCOUNT_CREATE_RESPONSE,
	WORLD_CLIENT_DELETE_CHARACTER_RESPONSE,
	WORLD_CLIENT_GAME_MSG,
	WORLD_CLIENT_CONNECT_CHAT,
	WORLD_CLIENT_TRANSFER_TO_WORLD,
	WORLD_CLIENT_IMPENDING_RELOAD_NOTIFY,
	WORLD_CLIENT_MAKE_GM_RESPONSE,
	WORLD_CLIENT_HTTP_MONITOR_INFO_RESPONSE,
	WORLD_CLIENT_SLASH_PUSH_MAP_RESPONSE,
	WORLD_CLIENT_SLASH_PULL_MAP_RESPONSE,
	WORLD_CLIENT_SLASH_LOCK_MAP_RESPONSE,
	WORLD_CLIENT_BLUEPRINT_SAVE_RESPONSE,
	WORLD_CLIENT_BLUEPRINT_LUP_SAVE_RESPONSE,
	WORLD_CLIENT_BLUEPRINT_LOAD_RESPONSE_ITEMID,
	WORLD_CLIENT_BLUEPRINT_GET_ALL_DATA_RESPONSE,
	WORLD_CLIENT_MODEL_INSTANTIATE_RESPONSE,
	WORLD_CLIENT_DEBUG_OUTPUT,
	WORLD_CLIENT_ADD_FRIEND_REQUEST,
	WORLD_CLIENT_ADD_FRIEND_RESPONSE,
	WORLD_CLIENT_REMOVE_FRIEND_RESPONSE,
	WORLD_CLIENT_GET_FRIENDS_LIST_RESPONSE,
	WORLD_CLIENT_UPDATE_FRIEND_NOTIFY,
	WORLD_CLIENT_ADD_IGNORE_RESPONSE,
	WORLD_CLIENT_REMOVE_IGNORE_RESPONSE,
	WORLD_CLIENT_GET_IGNORE_LIST_RESPONSE,
	WORLD_CLIENT_TEAM_INVITE,
	WORLD_CLIENT_TEAM_INVITE_INITIAL_RESPONSE,
	WORLD_CLIENT_GUILD_CREATE_RESPONSE,
	WORLD_CLIENT_GUILD_GET_STATUS_RESPONSE,
	WORLD_CLIENT_GUILD_INVITE,
	WORLD_CLIENT_GUILD_INVITE_INITIAL_RESPONSE,
	WORLD_CLIENT_GUILD_INVITE_FINAL_RESPONSE,
	WORLD_CLIENT_GUILD_INVITE_CONFIRM,
	WORLD_CLIENT_GUILD_ADD_PLAYER,
	WORLD_CLIENT_GUILD_REMOVE_PLAYER,
	WORLD_CLIENT_GUILD_LOGIN_LOGOUT,
	WORLD_CLIENT_GUILD_RANK_CHANGE,
	WORLD_CLIENT_GUILD_DATA,
	WORLD_CLIENT_GUILD_STATUS,
	WORLD_CLIENT_MAIL,
	WORLD_CLIENT_DB_PROXY_RESULT,
	WORLD_CLIENT_SHOW_ALL_RESPONSE,
	WORLD_CLIENT_WHO_RESPONSE,
	WORLD_CLIENT_SEND_CANNED_TEXT,
	WORLD_CLIENT_UPDATE_CHARACTER_NAME,
	WORLD_CLIENT_SET_NETWORK_SIMULATOR,
	WORLD_CLIENT_INVALID_CHAT_MESSAGE,
	WORLD_CLIENT_MINIMUM_CHAT_MODE_RESPONSE,
	WORLD_CLIENT_MINIMUM_CHAT_MODE_RESPONSE_PRIVATE,
	WORLD_CLIENT_CHAT_MODERATION_STRING,
	WORLD_CLIENT_UGC_MANIFEST_RESPONSE,
	WORLD_CLIENT_IN_LOGIN_QUEUE,
	WORLD_CLIENT_SERVER_STATES,
	WORLD_CLIENT_GM_CLOSE_TARGET_CHAT_WINDOW,
	WORLD_CLIENT_GENERAL_TEXT_FOR_LOCALIZATION,
	WORLD_CLIENT_UPDATE_FREE_TRIAL_STATUS
};

enum DisconnectID : unsigned long
{
	DISCONNECT_UNKNOWN_SERVER_ERROR = 0x00,
	DISCONNECT_DUPLICATE_LOGIN = 0x04,
	DISCONNECT_SERVER_SHUTDOWN = 0x05,
	DISCONNECT_SERVER_UNABLE_TO_LOAD_MAP = 0x06,
	DISCONNECT_INVALID_TRANSITION_KEY = 0x07,
	DISCONNECT_ACCOUNT_NOT_IN_PENDING_LIST = 0x08,
	DISCONNECT_CHARACTER_NOT_FOUND = 0x09,
	DISCONNECT_CHARACTER_CORRUPTION = 0x0a,
	DISCONNECT_KICK = 0x0b,
	DISCONNECT_FREE_TRIAL_EXPIRED = 0x0d,
	DISCONNECT_PLAY_SCHEDULE_TIME_DONE = 0x0e
};

class Server
{
private:
	static ServerRole serverRole;
	static SocketDescriptor socketDescriptor;
	static NetworkIDManager networkIDManager;
	static ReplicaManager replicaManager;
	static RakPeerInterface* peerInterface;
public:
	static void init(ServerRole serverRole);
	static bool start();
	static void shutdown(int errorCode = 0);

	static ServerRole getServerRole();
	static RakPeerInterface* getPeerInterface();
	static ReplicaManager* getReplicaManager();

	static bool isAuthenticationInstance();
	static bool isCharactersInstance();
	static bool isWorldInstance();

	static void sendPacket(BitStream* bitStream, SystemAddress address);
	static void broadcastPacket(BitStream* bitStream, SystemAddress address);
};