#pragma once
#include "Common.h"

enum ZoneID : unsigned short
{
	ZONE_ID_VENTURE_EXPLORER = 1000,
	ZONE_ID_RETURN_TO_VENTURE_EXPLORER = 1001,
	ZONE_ID_AVANT_GARDENS = 1100,
	ZONE_ID_AVANT_GARDENS_SURVIVAL = 1101,
	ZONE_ID_SPIDER_QUEEN_BATTLE = 1102,
	ZONE_ID_BLOCK_YARD = 1150,
	ZONE_ID_AVANT_GROVE = 1151,
	ZONE_ID_NIMBUS_STATION = 1200,
	ZONE_ID_PET_COVE = 1201,
	ZONE_ID_VERTIGO_LOOP_RACETRACK = 1203,
	ZONE_ID_BATTLE_OF_NIMBUS_STATION = 1204,
	ZONE_ID_NIMBUS_ROCK = 1250,
	ZONE_ID_NIMBUS_ISLE = 1251,
	ZONE_ID_GNARLED_FOREST = 1300,
	ZONE_ID_CANYON_COVE = 1302,
	ZONE_ID_CHANTEY_SHANTEY = 1350,
	ZONE_ID_FORBIDDEN_VALLEY = 1400,
	ZONE_ID_FORBIDDEN_VALLEY_DRAGON = 1402,
	ZONE_ID_DRAGONMAW_CHASM = 1403,
	ZONE_ID_RAVEN_BLUFF = 1450,
	ZONE_ID_STARBASE_3001 = 1600,
	ZONE_ID_DEEP_FREEZE = 1601,
	ZONE_ID_ROBOT_CITY = 1602,
	ZONE_ID_MOON_BASE = 1603,
	ZONE_ID_PORTABELLO = 1604,
	ZONE_ID_LEGO_CLUB = 1700,
	ZONE_ID_CRUX_PRIME = 1800,
	ZONE_ID_NEXUS_TOWER = 1900,
	ZONE_ID_NINJAGO_MONASTERY = 2000,
	ZONE_ID_FRAKJAW_BATTLE = 2001,

	INVALID_ZONE_ID
};

class ZoneIDs
{
public:
	static ZoneID fromString(string str);
	static string toString(ZoneID zoneID);
	static string toPrintString(ZoneID zoneID);
	static vector<unsigned char> getChecksum(ZoneID zoneID);
};